# **Project 3 Report**

Jason Brown

CS458

In [14]:
import os
import numpy as np
from sklearn.datasets import fetch_20newsgroups
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import load_digits
from sklearn.neural_network import MLPClassifier
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.svm import NuSVC

## **P3-1. Revisit Text Document Classification**

**(a) Load the following 4 categories from the 20 newsgroups dataset: categories = ['rec.autos', 'talk.religion.misc', 'comp.graphics', 'sci.space'].**

In [3]:
cats = ['rec.autos', 'talk.religion.misc', 'comp.graphics', 'sci.space']
news_train = fetch_20newsgroups(subset='train', categories=cats, remove=('headers', 'footers', 'quotes'))
news_test = fetch_20newsgroups(subset='test', categories=cats,remove=('headers', 'footers', 'quotes'))


**(b)Build classifiers using the following methods:
 Support Vector Machine (sklearn.svm.LinearSVC)
 Naive Bayes classifiers (sklearn.naive_bayes.MultinomialNB)
 K-nearest neighbors (sklearn.neighbors.KNeighborsClassifier)
 Random forest (sklearn.ensemble.RandomForestClassifier)
 AdaBoost classifier (sklearn.ensemble.AdaBoostClassifier)
Optimize the hyperparameters of these methods and compare the results of these methods.**

In [5]:
vectorizer = TfidfVectorizer()
xtrain = vectorizer.fit_transform(news_train.data)
xtest = vectorizer.transform(news_test.data)

ytrain = news_train.target
ytest = news_test.target

#Linear Support Vector Machine
clf = svm.LinearSVC()
clf.fit(xtrain, ytrain)
ypred = clf.predict(xtest)
cr = classification_report(ytest, ypred)
print("********************* LINEAR SVM *********************")
print(cr)

#Naive Bayes Classifiers
clf = MultinomialNB()
clf.fit(xtrain, ytrain)
ypred = clf.predict(xtest)
cr = classification_report(ytest, ypred)
print("******************** NAIVE BAYES ********************")
print(cr)

#K Nearest Neighbors
clf = KNeighborsClassifier()
clf.fit(xtrain, ytrain)
ypred = clf.predict(xtest)
cr = classification_report(ytest, ypred)
print("**************** K NEAREST NEIGHBORS ****************")
print(cr)

#Random Forest
clf = RandomForestClassifier()
clf.fit(xtrain, ytrain)
ypred = clf.predict(xtest)
cr = classification_report(ytest, ypred)
print("******************* RANDOM FOREST *******************")
print(cr)

#AdaBoost Classifier
clf = AdaBoostClassifier()
clf.fit(xtrain, ytrain)
ypred = clf.predict(xtest)
cr = classification_report(ytest, ypred)
print("********************* ADABOOST *********************")
print(cr)

********************* LINEAR SVM *********************
              precision    recall  f1-score   support

           0       0.91      0.90      0.91       389
           1       0.81      0.91      0.86       396
           2       0.87      0.83      0.85       394
           3       0.90      0.79      0.84       251

    accuracy                           0.87      1430
   macro avg       0.87      0.86      0.86      1430
weighted avg       0.87      0.87      0.87      1430

******************** NAIVE BAYES ********************
              precision    recall  f1-score   support

           0       0.91      0.87      0.89       389
           1       0.75      0.94      0.84       396
           2       0.74      0.87      0.80       394
           3       1.00      0.37      0.54       251

    accuracy                           0.80      1430
   macro avg       0.85      0.77      0.77      1430
weighted avg       0.83      0.80      0.79      1430

**************** K NE

DISCUSS THEM HERE

# **P3-2. Recognizing Hand-Written Digits**

**(a) Develop a multi-layer perceptron classifier to recognize images of hand-written digits. To build your classifier

In [6]:
digits = load_digits()
X = digits.data
y = digits.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.5)

#MLP CLassifier with no parameters
clf = MLPClassifier()
clf.fit(X_train, y_train)
ypred = clf.predict(X_test)
cr = classification_report(y_test, ypred)
print("************** DEFAULT MLP CLASSIFIER ***************")
print(cr)
cm = confusion_matrix(y_test, ypred)
print("******* CONFUSION MATRIX *******")
print(cm)

************** DEFAULT MLP CLASSIFIER ***************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        90
           1       0.91      1.00      0.96        85
           2       0.98      1.00      0.99        90
           3       1.00      0.92      0.96        89
           4       1.00      0.99      0.99        85
           5       0.96      0.97      0.96        90
           6       0.99      0.96      0.97        99
           7       0.99      1.00      0.99        89
           8       0.91      0.88      0.89        90
           9       0.96      0.98      0.97        92

    accuracy                           0.97       899
   macro avg       0.97      0.97      0.97       899
weighted avg       0.97      0.97      0.97       899

******* CONFUSION MATRIX *******
[[90  0  0  0  0  0  0  0  0  0]
 [ 0 85  0  0  0  0  0  0  0  0]
 [ 0  0 90  0  0  0  0  0  0  0]
 [ 0  0  0 82  0  1  0  0  4  2]
 [ 0  0  0  0 84  0  0